from datetime import datetime
import os
import sqlite3
from werkzeug.security import generate_password_hash
from flask import Blueprint, render_template, request, redirect, session, url_for, flash

from helpers import admin_required, get_db, log_audit, login_required

members_bp = Blueprint('members', __name__)


@members_bp.route('/members')
@login_required
def list_members():
    try:
        with get_db() as conn:
            db = conn.cursor()

            db.execute("SELECT * FROM members ORDER BY id DESC")
            members_from_db = db.fetchall()

            # Convert date format for display
            members_list = []
            for m in members_from_db:
                m = dict(m)  # convert Row object to regular dict so it's mutable
                if m['date_joined']:
                    m['date_joined'] = datetime.strptime(m['date_joined'], '%Y-%m-%d').strftime('%d-%m-%Y')
                members_list.append(m)

            db.execute("SELECT COUNT(*) as count FROM members WHERE status = 'active'")
            total_members = db.fetchone()['count']

            db.execute("""
                SELECT COALESCE(AVG(total), 0) as avg
                FROM (
                    SELECT SUM(amount) as total
                    FROM contributions
                    GROUP BY member_id
                )
            """)
            avg_contribution = db.fetchone()['avg']

            db.execute("""
                SELECT COUNT(*) as count FROM members WHERE status = 'active'
            """)
            active_count = db.fetchone()['count']

            active_share = round((active_count / total_members * 100), 1) if total_members > 0 else 0

        return render_template('members.html',
            active_page='members',
            members=members_list,
            total_members=total_members,
            avg_contribution=avg_contribution,
            active_share=active_share
        )
    except sqlite3.Error as e:
        flash(f"Failed to load members: {str(e)}", "error")
        return render_template('members.html',
            active_page='members',
            members=[],
            total_members=0,
            avg_contribution=0,
            active_share=0
        )
    
    

@members_bp.route('/members/add', methods=['GET', 'POST'])
def add_member():
    if request.method == 'POST':

        # 1. Extract form fields
        full_name = request.form.get('fullName', '').strip().title()
        username  = request.form.get('username', '').strip()
        phone     = request.form.get('phone', '').strip()
        email     = request.form.get('email', '').strip()
        address   = request.form.get('address', '').strip()
        profile   = request.form.get('profile', '').strip()
        password  = request.form.get('password', '')
        cpassword = request.form.get('Cpassword', '')

        # 2. Validate passwords before touching the database
        if password != cpassword:
            flash("Password and confirm password do not match.", "error")
            return render_template('add_member.html', active_page='members')

        # 3. Hash — never store raw text
        password_hash = generate_password_hash(password)

        # 4. Insert
        try:
            with get_db() as conn:
                db = conn.cursor()
                db.execute("""
                    INSERT INTO members (
                        full_name, password_hash, username, phone, email, address, profile_photo
                    ) VALUES (?, ?, ?, ?, ?, ?, ?)
                """, (full_name, password_hash, username, phone, email, address, profile))

                # Capture the auto-incremented ID generated by SQLite for this new row
                new_member_id = db.lastrowid
                
                # Trigger the audit log tracking payload
                log_audit(
                    db=db, 
                    action='create', 
                    table_name='members', 
                    record_id=new_member_id,
                    description=f"New member account created for {full_name}",
                    member_id=session.get('user_id')  # Tracks WHOM did it (logged-in admin/user)
                )

                conn.commit()

            flash(f"Account created for {full_name}.", "success")
            return redirect(url_for('members.list_members'))

        except sqlite3.IntegrityError:
            flash("Username or email already exists. Please choose another.", "error")
            return render_template('add_member.html', active_page='members')

        except sqlite3.Error as e:
            flash(f"Database error: {str(e)}", "error")
            return render_template('add_member.html', active_page='members')

    return render_template('add_member.html', active_page='members')



# Handle Recording of New Contributions Workflow Pipeline
@members_bp.route('/contributions/record', methods=['GET', 'POST'])
@login_required
def record_contribution():
    if request.method == 'POST':
        member_id = request.form.get('member_id')
        amount = float(request.form.get('amount') or 0)
        method = request.form.get('method', 'Bank Transfer')
        reference = request.form.get('reference', '').strip()
        notes = request.form.get('notes', '').strip()

        if not member_id or amount <= 0:
            flash("Invalid input. Please check the amount and member selection.", "error")
            return redirect(url_for('members.record_contribution'))

        try:
            with get_db() as conn:
                db = conn.cursor()

                # 1. Get member name for the transaction description
                db.execute("SELECT full_name FROM members WHERE id = ?", (member_id,))
                member = db.fetchone()
                if not member:
                    flash("Member not found.", "error")
                    return redirect(url_for('members.record_contribution'))
                
                # Extract clean name from row result
                member_name = member[0] if isinstance(member, tuple) else member['full_name']

                # 2. Insert into contributions table
                db.execute("""
                    INSERT INTO contributions (
                        member_id, amount, payment_method, reference, notes, created_by
                    ) VALUES (?, ?, ?, ?, ?, ?)
                """, (member_id, amount, method, reference, notes, session['user_id']))

                # Capture the newly generated Contribution ID for Python to use in audit log
                new_contribution_id = db.lastrowid

                # 3. Log in transactions table — using python variable for consistency
                db.execute("""
                    INSERT INTO transactions (
                        transaction_type, amount, description,
                        reference_id, reference_table, created_by
                    ) VALUES ('contribution', ?, ?, ?, 'contributions', ?)
                """, (
                    amount,
                    f"Contribution of ₦{amount:,.2f} via {method} by {member_name} — {reference}",
                    new_contribution_id,
                    session['user_id']
                ))

                # 4. Trigger the audit log wrapper
                log_audit(
                    db=db, 
                    action='create', 
                    table_name='contributions', 
                    record_id=new_contribution_id,
                    description=f"Contribution of ₦{amount:,.2f} recorded for member: {member_name} (ID: {member_id})",
                    member_id=session.get('user_id')
                )
                                    
                conn.commit()

            flash("Contribution recorded successfully.", "success")
            return redirect(url_for('transactions.list_transactions'))

        except sqlite3.Error as e:
            flash(f"Database error: {str(e)}", "error")
            return redirect(url_for('members.record_contribution'))

    # GET — only fetch columns that actually exist
    try:
        with get_db() as conn:
            db = conn.cursor()
            db.execute("""
                SELECT
                    m.id,
                    m.full_name,
                    m.username,
                    COALESCE(SUM(c.amount), 0) as total_contributions
                FROM members m
                LEFT JOIN contributions c ON c.member_id = m.id
                WHERE m.status = 'active'
                GROUP BY m.id
                ORDER BY m.full_name ASC
            """)
            active_members = db.fetchall()
    except sqlite3.Error:
        active_members = []

    return render_template('contribution.html', active_page='members', members_list=active_members)
